name: dart_casing
description: Dart library for changing String case style to the desired convention.
version: 3.0.1
homepage: https://jesway.com
repository: https://github.com/Jesway/Dart-Casing

environment:
  sdk: '>=3.1.1 <4.0.0'
  
dev_dependencies:
  test: 1.24.6