name: dart_casing
description: Dart library for changing String case style to the desired convention.
version: 2.0.0
homepage: https://bratan.me
repository: https://github.com/bratan/dart_casing

environment:
  sdk: '>=2.12.0 <3.0.0'
